sudo: required

language: cpp

services:
  - docker

install:
  - docker pull rkalkani/docker-nacl-webports

script:
  - docker run -td -v `pwd`:/home/project --name nacl rkalkani/docker-nacl-webports
  - docker exec nacl /bin/bash -c "cd /home/project/Counter; make"
  - docker exec nacl /bin/bash -c "cd /home/project/GettingStarted; make"
  - docker exec nacl /bin/bash -c "cd /home/project/Simple; make"
  - docker exec nacl /bin/bash -c "cd /home/project/MonteCarlo; make"
  - docker exec nacl /bin/bash -c "cd /home/project/ImageProc; make"

